### ISSUE TITLE
Error: module "bind" not found from "engine.io-reconnect/lib/index.js"

### ISSUE THREAD

**Issue by yocontra** [cayasso/engine.io-reconnect#2]
Happens during a browserify build. Probably just missing a dep

**Comment by ColemanGariety** [comment]
I'm getting the same issue when browserifying.

**Comment by cayasso** [comment]
Sorry for the delay on this, I will take a look today, recently `engine.io` was updated to use `browserify` for builds and no longer `component`, so this error might be related.

**Comment by cayasso** [comment]
Hey @Contra @JacksonGariety  this commit should resolve this issue, thanks for reporting!!! https://github.com/cayasso/engine.io-reconnect/commit/7330cfbcd8660a6f00fbe42fedcaf7fa6d11c8b3
